version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          SPURWING_PID: ${SPURWING_PID}
          SPURWING_KEY: ${SPURWING_KEY}
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python spurwing/test_api.py
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build